# Change these first
owner: d4khosting # Your GitHub organization or username, where this repository lives
repo: uptime-d4kstatus-net # The name of this repository

sites:
  - name: Web Hosting Server
    url: https://vps.d4kservers.net
    icon: https://raw.githubusercontent.com/d4khosting/uptime-d4kstatus-net/master/assets/internet-favicon-01.svg
  - name: Mail Services
    check: "tcp-ping"
    url: 51.79.73.167
    icon: https://raw.githubusercontent.com/d4khosting/uptime-d4kstatus-net/master/assets/mail-favicon-01.svg
    port: 993
  - name: Control Panel
    check: "tcp-ping"
    url: 51.79.73.167
    icon: https://raw.githubusercontent.com/d4khosting/uptime-d4kstatus-net/master/assets/d4k-hosting-favicon.svg
    port: 2083

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: www.d4kstatus.net
  # baseUrl: /your-repo-name
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  themeUrl: https://raw.githubusercontent.com/d4khosting/uptime-d4kstatus-net/master/assets/d4k-status.css
  name: D4K Hosting Status
  introTitle: "**Uptime Status for D4K Hosting**"
  introMessage: Real-time status and historical uptime records of the D4K web server and hosting services. During an outage, updates will be posted here. Contact D4K Hosting by email at [support@hosting.ca](mailto:support@hosting.ca) if your website is down even though the web hosting server below is up.
  metaTags:
    - name: "robots"
      content: "noindex"
  navbar:
    - title: Status
      href: /
    - title: D4K Hosting
      href: https://www.d4khosting.ca

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
