owner: d4khosting 
repo: uptime-d4kstatus-net 

sites:
  - name: CAN West Server (Vancouver)
    url: https://vps.d4khosting.net
    slug: d4k-hosting-net
    icon: https://d4khosting.github.io/uptime-assets/images/internet-favicon-01.svg
  - name: CAN East Server (Montreal)
    url: https://vps.d4kservers.net
    slug: d4k-servers-net
    icon: https://d4khosting.github.io/uptime-assets/images/internet-favicon-01.svg

status-website:
  cname: www.d4kstatus.net
  favicon: https://d4khosting.github.io/uptime-assets/images/d4k-hosting-favicon-192x192.png
  faviconSvg: https://d4khosting.github.io/uptime-assets/images/d4k-hosting-favicon.svg
  logoUrl: https://d4khosting.github.io/uptime-assets/images/d4k-hosting-logo-2023.svg
  links:
    - rel: preconnect
      href: https://fonts.googleapis.com
    - rel: preconnect
      href: https://fonts.gstatic.com
    - rel: stylesheet
      href: https://fonts.googleapis.com/css2?family=Atkinson+Hyperlegible:wght@400;700&display=swap
    - rel: stylesheet
      href: https://d4khosting.github.io/uptime-assets/css/d4k-status.css
  name: D4K Hosting Status
  introTitle: "**Uptime Status for D4K Hosting**"
  introMessage: Real-time status and historical uptime records of D4K web hosting servers. During an outage, updates will be posted here. For regular hosting support, contact D4K Hosting by email at [support@hosting.ca](mailto:support@hosting.ca).
  metaTags:
    - name: "robots"
      content: "noindex"

i18n:
  locale: en-CA
