# Change these first
owner: d4khosting # Your GitHub organization or username, where this repository lives
repo: uptime-d4kstatus-net # The name of this repository

sites:
  - name: D4K Hosting Server
    url: https://www.d4khosting.ca
    slug: d4k-hosting-server
    icon: https://www.d4khosting.ca/favicon.ico

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: www.d4kstatus.net
  # baseUrl: /your-repo-name
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: D4K Hosting Status
  introTitle: "**Upptime** is the open-source uptime monitor and status page, powered entirely by GitHub."
  introMessage: This is a sample status page which uses **real-time** data from our [GitHub repository](https://github.com/upptime/upptime). No server required — just GitHub Actions, Issues, and Pages. [**Get your own for free**](https://github.com/upptime/upptime)
  metaTags:
    - name: "robots"
      content: "noindex"
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
